/**
 * 태스크 Repository
 * tasks 테이블에 대한 CRUD 연산을 제공합니다.
 */

import { getDB, saveDB } from '../index'

export interface CreateTaskData {
  projectId: number
  meetingId?: number
  title: string
  description?: string
  status?: string
  assignee?: string
  priority?: string
  tags?: string[]
  dueDate?: string
  isAutoGenerated?: boolean
}

export interface UpdateTaskData {
  title?: string
  description?: string
  status?: string
  assignee?: string
  priority?: string
  tags?: string[]
  dueDate?: string
  meetingId?: number
}

export const taskRepository = {
  /**
   * 프로젝트별 태스크를 최신순으로 조회합니다.
   */
  getByProject(projectId: number): Record<string, unknown>[] {
    const db = getDB()
    const stmt = db.prepare(
      'SELECT * FROM tasks WHERE project_id = ? ORDER BY created_at DESC'
    )
    stmt.bind([projectId])
    const rows: Record<string, unknown>[] = []
    while (stmt.step()) rows.push(stmt.getAsObject())
    stmt.free()
    return rows
  },

  /**
   * ID로 태스크를 조회합니다.
   */
  getById(id: number): Record<string, unknown> | null {
    const db = getDB()
    const stmt = db.prepare('SELECT * FROM tasks WHERE id = ?')
    stmt.bind([id])
    const result = stmt.step() ? stmt.getAsObject() : null
    stmt.free()
    return result
  },

  /**
   * 태스크를 생성합니다.
   */
  create(data: CreateTaskData): Record<string, unknown> {
    const db = getDB()
    db.run(
      `INSERT INTO tasks 
       (project_id, meeting_id, title, description, status, assignee, priority, tags, due_date, is_auto_generated) 
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        data.projectId,
        data.meetingId ?? null,
        data.title,
        data.description ?? null,
        data.status ?? 'todo',
        data.assignee ?? null,
        data.priority ?? 'medium',
        data.tags ? JSON.stringify(data.tags) : null,
        data.dueDate ?? null,
        data.isAutoGenerated ? 1 : 0
      ]
    )
    saveDB()

    const stmt = db.prepare('SELECT * FROM tasks ORDER BY id DESC LIMIT 1')
    stmt.step()
    const row = stmt.getAsObject()
    stmt.free()
    return row
  },

  /**
   * 태스크 상태를 변경합니다.
   */
  updateStatus(id: number, status: string): Record<string, unknown> | null {
    const db = getDB()
    db.run(
      "UPDATE tasks SET status = ?, updated_at = datetime('now') WHERE id = ?",
      [status, id]
    )
    saveDB()
    return this.getById(id)
  },

  /**
   * 태스크를 수정합니다.
   */
  update(id: number, data: UpdateTaskData): Record<string, unknown> | null {
    const db = getDB()
    const fields: string[] = []
    const values: (string | number | null)[] = []

    if (data.title !== undefined) {
      fields.push('title = ?')
      values.push(data.title)
    }
    if (data.description !== undefined) {
      fields.push('description = ?')
      values.push(data.description)
    }
    if (data.status !== undefined) {
      fields.push('status = ?')
      values.push(data.status)
    }
    if (data.assignee !== undefined) {
      fields.push('assignee = ?')
      values.push(data.assignee)
    }
    if (data.priority !== undefined) {
      fields.push('priority = ?')
      values.push(data.priority)
    }
    if (data.tags !== undefined) {
      fields.push('tags = ?')
      values.push(JSON.stringify(data.tags))
    }
    if (data.dueDate !== undefined) {
      fields.push('due_date = ?')
      values.push(data.dueDate)
    }
    if (data.meetingId !== undefined) {
      fields.push('meeting_id = ?')
      values.push(data.meetingId)
    }

    if (fields.length === 0) return this.getById(id)

    fields.push("updated_at = datetime('now')")
    values.push(id)

    db.run(`UPDATE tasks SET ${fields.join(', ')} WHERE id = ?`, values)
    saveDB()
    return this.getById(id)
  },

  /**
   * 태스크를 삭제합니다.
   */
  delete(id: number): boolean {
    const db = getDB()
    db.run('DELETE FROM tasks WHERE id = ?', [id])
    saveDB()
    return db.getRowsModified() > 0
  },

  /**
   * 미완료 태스크를 조회합니다.
   */
  getIncomplete(projectId: number): Record<string, unknown>[] {
    const db = getDB()
    const stmt = db.prepare(
      `SELECT * FROM tasks 
       WHERE project_id = ? AND status != 'done' 
       ORDER BY 
         CASE priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 WHEN 'low' THEN 2 END,
         created_at DESC`
    )
    stmt.bind([projectId])
    const rows: Record<string, unknown>[] = []
    while (stmt.step()) rows.push(stmt.getAsObject())
    stmt.free()
    return rows
  },

  /**
   * 상태별 태스크를 조회합니다.
   */
  getByStatus(projectId: number, status: string): Record<string, unknown>[] {
    const db = getDB()
    const stmt = db.prepare(
      'SELECT * FROM tasks WHERE project_id = ? AND status = ? ORDER BY created_at DESC'
    )
    stmt.bind([projectId, status])
    const rows: Record<string, unknown>[] = []
    while (stmt.step()) rows.push(stmt.getAsObject())
    stmt.free()
    return rows
  },

  /**
   * 회의록에 연결된 태스크를 조회합니다.
   */
  getByMeeting(meetingId: number): Record<string, unknown>[] {
    const db = getDB()
    const stmt = db.prepare(
      'SELECT * FROM tasks WHERE meeting_id = ? ORDER BY created_at DESC'
    )
    stmt.bind([meetingId])
    const rows: Record<string, unknown>[] = []
    while (stmt.step()) rows.push(stmt.getAsObject())
    stmt.free()
    return rows
  }
}
