import { contextBridge, ipcRenderer } from 'electron'
import type { QueryRequest } from '../shared/types'

// renderer에서 사용할 수 있는 API를 window.api로 노출
contextBridge.exposeInMainWorld('api', {
  // ── 프로젝트 ─────────────────────────────────────────────
  getProjects: () => ipcRenderer.invoke('projects:getAll'),
  getProjectById: (id: number) => ipcRenderer.invoke('projects:getById', id),
  createProject: (data: { name: string; description?: string; gitPath?: string; goal?: string }) =>
    ipcRenderer.invoke('projects:create', data),
  updateProject: (id: number, data: { name?: string; description?: string; gitPath?: string; status?: string; goal?: string }) =>
    ipcRenderer.invoke('projects:update', id, data),
  deleteProject: (id: number) => ipcRenderer.invoke('projects:delete', id),
  getActiveProjects: () => ipcRenderer.invoke('projects:getActive'),

  // ── 회의록 ───────────────────────────────────────────────
  getMeetings: (projectId: number) => ipcRenderer.invoke('meetings:getByProject', projectId),
  getMeetingById: (id: number) => ipcRenderer.invoke('meetings:getById', id),
  createMeeting: (data: { projectId: number; title: string; content: string; date: string }) =>
    ipcRenderer.invoke('meetings:create', data),
  updateMeeting: (id: number, data: { title?: string; content?: string; date?: string; summary?: string }) =>
    ipcRenderer.invoke('meetings:update', id, data),
  deleteMeeting: (id: number) => ipcRenderer.invoke('meetings:delete', id),
  getRecentMeetings: (limit: number) => ipcRenderer.invoke('meetings:getRecent', limit),
  searchMeetings: (projectId: number, keyword: string) =>
    ipcRenderer.invoke('meetings:search', projectId, keyword),

  // ── 태스크 ───────────────────────────────────────────────
  getTasks: (projectId: number) => ipcRenderer.invoke('tasks:getByProject', projectId),
  getTaskById: (id: number) => ipcRenderer.invoke('tasks:getById', id),
  createTask: (data: {
    projectId: number
    title: string
    status?: string
    priority?: string
    assignee?: string
    description?: string
    meetingId?: number
    tags?: string[]
    dueDate?: string
    isAutoGenerated?: boolean
  }) => ipcRenderer.invoke('tasks:create', data),
  updateTaskStatus: (id: number, status: string) =>
    ipcRenderer.invoke('tasks:updateStatus', id, status),
  updateTask: (id: number, data: {
    title?: string
    description?: string
    status?: string
    assignee?: string
    priority?: string
    tags?: string[]
    dueDate?: string
    meetingId?: number
  }) => ipcRenderer.invoke('tasks:update', id, data),
  deleteTask: (id: number) => ipcRenderer.invoke('tasks:delete', id),
  getIncompleteTasks: (projectId: number) => ipcRenderer.invoke('tasks:getIncomplete', projectId),
  getTasksByStatus: (projectId: number, status: string) =>
    ipcRenderer.invoke('tasks:getByStatus', projectId, status),
  getTasksByMeeting: (meetingId: number) => ipcRenderer.invoke('tasks:getByMeeting', meetingId),

  // ── 문서 ─────────────────────────────────────────────────
  selectDocumentFolder: () => ipcRenderer.invoke('documents:selectFolder'),
  selectDocumentFiles: () => ipcRenderer.invoke('documents:selectFiles'),
  scanDocuments: (data: { projectId: number; folderPath: string }) =>
    ipcRenderer.invoke('documents:scan', data),
  addDocumentFiles: (data: { projectId: number; filePaths: string[] }) =>
    ipcRenderer.invoke('documents:addFiles', data),
  getDocuments: (projectId: number) => ipcRenderer.invoke('documents:getByProject', projectId),
  deleteDocument: (id: number) => ipcRenderer.invoke('documents:delete', id),
  deleteAllDocuments: (projectId: number) => ipcRenderer.invoke('documents:deleteByProject', projectId),
  readDocumentContent: (filePath: string) => ipcRenderer.invoke('documents:readContent', filePath),

  // ── 질의 ─────────────────────────────────────────────────
  query: (request: QueryRequest) => ipcRenderer.invoke('query:run', request),
  getQueryHistory: (projectId: number, limit?: number) =>
    ipcRenderer.invoke('query:getHistory', projectId, limit),
  getQueryById: (id: number) => ipcRenderer.invoke('query:getById', id),
  submitEvidenceFeedback: (data: any) => ipcRenderer.invoke('evidence:feedback', data),
  submitAllEvidenceFeedback: (data: any) => ipcRenderer.invoke('evidence:submitAll', data),
  getAdaptiveParams: (userId: string) => ipcRenderer.invoke('adaptive:getParams', userId),

  // ── Git ──────────────────────────────────────────────────
  validateGitRepo: (repoPath: string) => ipcRenderer.invoke('git:validate', repoPath),
  getGitRepoInfo: (repoPath: string) => ipcRenderer.invoke('git:repoInfo', repoPath),
  getGitCommits: (repoPath: string, count?: number) =>
    ipcRenderer.invoke('git:recentCommits', repoPath, count),
  getGitCommitDetail: (repoPath: string, commitHash: string) =>
    ipcRenderer.invoke('git:commitDetail', repoPath, commitHash),
  selectGitFolder: () => ipcRenderer.invoke('git:selectFolder')
})
