/**
 * window.api 타입 선언
 * preload에서 노출한 API 메서드의 타입을 정의합니다.
 */

export {}

declare global {
  interface Window {
    api: {
      // 프로젝트
      getProjects: () => Promise<Record<string, unknown>[]>
      getProjectById: (id: number) => Promise<Record<string, unknown> | null>
      createProject: (data: { name: string; description?: string; gitPath?: string; goal?: string }) => Promise<Record<string, unknown>>
      updateProject: (id: number, data: { name?: string; description?: string; gitPath?: string; status?: string; goal?: string }) => Promise<Record<string, unknown> | null>
      deleteProject: (id: number) => Promise<boolean>
      getActiveProjects: () => Promise<Record<string, unknown>[]>

      // 회의록
      getMeetings: (projectId: number) => Promise<Record<string, unknown>[]>
      getMeetingById: (id: number) => Promise<Record<string, unknown> | null>
      createMeeting: (data: { projectId: number; title: string; content: string; date: string }) => Promise<Record<string, unknown>>
      updateMeeting: (id: number, data: { title?: string; content?: string; date?: string; summary?: string }) => Promise<Record<string, unknown> | null>
      deleteMeeting: (id: number) => Promise<boolean>
      getRecentMeetings: (limit: number) => Promise<Record<string, unknown>[]>
      searchMeetings: (projectId: number, keyword: string) => Promise<Record<string, unknown>[]>

      // 태스크
      getTasks: (projectId: number) => Promise<Record<string, unknown>[]>
      getTaskById: (id: number) => Promise<Record<string, unknown> | null>
      createTask: (data: {
        projectId: number
        title: string
        status?: string
        priority?: string
        assignee?: string
        description?: string
        meetingId?: number
        tags?: string[]
        dueDate?: string
        isAutoGenerated?: boolean
      }) => Promise<Record<string, unknown>>
      updateTaskStatus: (id: number, status: string) => Promise<Record<string, unknown> | null>
      updateTask: (id: number, data: {
        title?: string; description?: string; status?: string
        assignee?: string; priority?: string; tags?: string[]
        dueDate?: string; meetingId?: number
      }) => Promise<Record<string, unknown> | null>
      deleteTask: (id: number) => Promise<boolean>
      getIncompleteTasks: (projectId: number) => Promise<Record<string, unknown>[]>
      getTasksByStatus: (projectId: number, status: string) => Promise<Record<string, unknown>[]>
      getTasksByMeeting: (meetingId: number) => Promise<Record<string, unknown>[]>

      // 문서
      selectDocumentFolder: () => Promise<{ path: string | null }>
      scanDocuments: (data: { projectId: number; folderPath: string }) => Promise<{ error: string | null; count: number; total?: number }>
      getDocuments: (projectId: number) => Promise<Record<string, unknown>[]>
      deleteDocument: (id: number) => Promise<boolean>
      deleteAllDocuments: (projectId: number) => Promise<number>

      // 질의
      query: (request: { projectId: number; sources: string[]; tool: string; prompt: string }) => Promise<{
        summary: string; evidence: unknown[]; suggestedActions: string[]; rawResponse?: string
      }>
      getQueryHistory: (projectId: number, limit?: number) => Promise<Record<string, unknown>[]>
      getQueryById: (id: number) => Promise<Record<string, unknown> | null>

      // Git
      validateGitRepo: (path: string) => Promise<{ valid: boolean; error: string | null }>
      getGitRepoInfo: (path: string) => Promise<{ data: { path: string; currentBranch: string; totalCommits: number; lastCommitDate: string; remoteUrl?: string } | null; error: string | null }>
      getGitCommits: (path: string, count?: number) => Promise<{ data: { hash: string; shortHash: string; message: string; author: string; date: string; changedFiles?: { path: string; status: string; additions: number; deletions: number }[] }[]; error: string | null }>
      getGitCommitDetail: (path: string, hash: string) => Promise<{ data: { hash: string; shortHash: string; message: string; author: string; date: string; changedFiles?: { path: string; status: string; additions: number; deletions: number }[] } | null; error: string | null }>
      selectGitFolder: () => Promise<{ path: string | null; valid?: boolean }>

      [key: string]: unknown
    }
  }
}
