// ── 데이터 소스 & 툴 타입 ──────────────────────────────────────

export type DataSource = 'git' | 'meetings' | 'tasks' | 'documents'

export type ToolType =
  | 'git-progress-analyzer'
  | 'meeting-summarizer'
  | 'task-status-query'
  | 'cross-source-summary'
  | 'document-search'
  | 'report-generator'

// ── Evidence ────────────────────────────────────────────────────

export interface EvidenceItem {
  id: string
  source: DataSource
  title: string
  content: string
  date?: string
  score: number
  metadata?: Record<string, unknown>
}

// ── 질의 요청/응답 ─────────────────────────────────────────────

export interface QueryRequest {
  projectId: number
  sources: DataSource[]
  tool: ToolType
  prompt: string
}

export interface QueryResponse {
  summary: string
  evidence: EvidenceItem[]
  suggestedActions: string[]
  rawResponse?: string
}

// ── 프로젝트 ────────────────────────────────────────────────────

export type ProjectStatus = 'active' | 'archived' | 'completed'

export interface Project {
  id: number
  name: string
  description?: string
  gitPath?: string
  status: ProjectStatus
  goal?: string
  createdAt: string
  updatedAt: string
}

// ── 회의록 ──────────────────────────────────────────────────────

export interface Meeting {
  id: number
  projectId: number
  title: string
  content: string
  summary?: string
  date: string
  createdAt: string
  updatedAt: string
}

// ── 태스크 ──────────────────────────────────────────────────────

export type TaskStatus = 'todo' | 'in_progress' | 'done'
export type TaskPriority = 'low' | 'medium' | 'high'

export interface Task {
  id: number
  projectId: number
  meetingId?: number
  title: string
  description?: string
  status: TaskStatus
  assignee?: string
  priority: TaskPriority
  tags?: string[]
  dueDate?: string
  isAutoGenerated: boolean
  createdAt: string
  updatedAt: string
}

// ── 문서 소스 ───────────────────────────────────────────────────

export interface DocumentSource {
  id: number
  projectId: number
  filePath: string
  fileName: string
  fileType: string
  fileSize?: number
  contentHash?: string
  lastIndexedAt?: string
  createdAt: string
  updatedAt: string
}

// ── Evidence 로그 ───────────────────────────────────────────────

export interface EvidenceLog {
  id: number
  queryLogId: number
  source: DataSource
  title: string
  content: string
  score?: number
  metadata?: string
  createdAt: string
}

// ── 보고서 ──────────────────────────────────────────────────────

export type ReportType = 'report' | 'presentation' | 'summary'

export interface Report {
  id: number
  projectId: number
  title: string
  type: ReportType
  content: string
  generatedBy?: string
  createdAt: string
  updatedAt: string
}

// ── 마일스톤 ────────────────────────────────────────────────────

export type MilestoneStatus = 'pending' | 'in_progress' | 'completed'

export interface Milestone {
  id: number
  projectId: number
  title: string
  description?: string
  dueDate?: string
  status: MilestoneStatus
  createdAt: string
  updatedAt: string
}

// ── 쿼리 로그 ───────────────────────────────────────────────────

export type QueryLogStatus = 'pending' | 'success' | 'error'

export interface QueryLog {
  id: number
  projectId: number
  sources: string
  tool: string
  prompt: string
  response?: string
  status: QueryLogStatus
  durationMs?: number
  createdAt: string
}

// ── AI 로그 ─────────────────────────────────────────────────────

export interface AiLog {
  id: number
  queryLogId: number
  model?: string
  promptSent?: string
  rawResponse?: string
  tokenUsed?: number
  error?: string
  createdAt: string
}

// ── Git 관련 (기존) ─────────────────────────────────────────────

export interface GitChangedFile {
  path: string
  status: 'added' | 'modified' | 'deleted' | 'renamed'
  additions: number
  deletions: number
}

export interface GitCommit {
  hash: string
  shortHash: string
  message: string
  author: string
  date: string
  changedFiles?: GitChangedFile[]
}

export interface GitRepoInfo {
  path: string
  currentBranch: string
  totalCommits: number
  lastCommitDate: string
  remoteUrl?: string
}
