import { IpcMain } from 'electron'
import { taskRepository } from '../database/repositories'

export function registerTaskHandlers(ipcMain: IpcMain): void {
  ipcMain.handle('tasks:getByProject', (_event, projectId: number) => {
    return taskRepository.getByProject(projectId)
  })

  ipcMain.handle('tasks:getById', (_event, id: number) => {
    return taskRepository.getById(id)
  })

  ipcMain.handle(
    'tasks:create',
    (
      _event,
      data: {
        projectId: number
        title: string
        status?: string
        priority?: string
        assignee?: string
        description?: string
        meetingId?: number
        tags?: string[]
        dueDate?: string
        isAutoGenerated?: boolean
      }
    ) => {
      return taskRepository.create(data)
    }
  )

  ipcMain.handle('tasks:updateStatus', (_event, id: number, status: string) => {
    return taskRepository.updateStatus(id, status)
  })

  ipcMain.handle(
    'tasks:update',
    (_event, id: number, data: {
      title?: string
      description?: string
      status?: string
      assignee?: string
      priority?: string
      tags?: string[]
      dueDate?: string
      meetingId?: number
    }) => {
      return taskRepository.update(id, data)
    }
  )

  ipcMain.handle('tasks:delete', (_event, id: number) => {
    return taskRepository.delete(id)
  })

  ipcMain.handle('tasks:getIncomplete', (_event, projectId: number) => {
    return taskRepository.getIncomplete(projectId)
  })

  ipcMain.handle('tasks:getByStatus', (_event, projectId: number, status: string) => {
    return taskRepository.getByStatus(projectId, status)
  })

  ipcMain.handle('tasks:getByMeeting', (_event, meetingId: number) => {
    return taskRepository.getByMeeting(meetingId)
  })
}
